import type { Metadata } from "next";
import "../styles/App.scss";
import React from "react";
import ClientLayout from "@/components/_layouts/clientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
    {/*<Head>
        <link rel="icon" href="/favicon.ico" sizes="any"/>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg"/>
    </Head>*/}
      <body>
      <ClientLayout>
        {children}
      </ClientLayout>
      </body>
    </html>
  );
}
